module.exports = {
    currentSelector: '//*[@id="header"]',
    selectorPicture: "",
    selectorHtmlPath: "",
    currentInnerText: "This is header",
    parentIframe: [],
    x: null,
    y: null,
    width: null,
    height: null,
    lastOperationTime: null,
    lastOperationTimeoutMs: null,
    currentOpeartion: null,
    currentSelectedIndex: 0,
    __htmlCaptureInProcess: [],
    recommendedLocator: [],
    potentialMatch: [
        {
            Locator: ["#header"],
            screenshot: "componentPic/Header.png",
            path: "Header",
            selector: null,
        },
    ],
    framePotentialMatch: [],
}